dependencies:
  - cdsapi
  - numpy
  - netCDF4
  - xarray
  - matplotlib
  - cartopy
  - geopandas
  - pandas
  - scipy
  - plotly
  - folium
  - seaborn
  - tqdm
  - regionmask
  - rioxarray
  - jupyterlab-myst
